version: '3.0'
services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/test
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:14
    env_file:
      - .development.env
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  pgdata:
  redis: